---
api_healthcheck:
  restcountries_url: "https://restcountries.com/v3.1/name/belgium"
  openlibrary_url: "https://openlibrary.org/works/OL15626917W.json"
  openlibrary_user_agent: "labo09-ansible-healthcheck/1.0"
  report_path: "{{ playbook_dir }}/../artifacts/api_healthcheck/report.json"
  github:
    gist_id: "95e81de3510d9249e5c40e0ca12a61ea"
    filename: "api_healthcheck_report.json"
    description: "API Healthcheck Report - Labo 09"
