all:
  children:
    linux:
      hosts:
        rocky1:
          ansible_host: 172.16.120.11
          ansible_user: administrator
          ansible_ssh_private_key_file: /home/axel/.ssh/id_ed25519_iac
        debian1:
          ansible_host: 172.16.120.13
          ansible_user: axel
          ansible_ssh_private_key_file: /home/axel/.ssh/id_ed25519_iac
    jumpbox:
      hosts:
        rocky1:
    service_host:
      hosts:
        debian1:
